// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN2rR1AjaDy98cp7UTwso8HFd9g0QsxbI',
    appId: '1:373805444677:web:0846452b560cdf8c77fd2c',
    messagingSenderId: '373805444677',
    projectId: 'payroll-database-cbd05',
    authDomain: 'payroll-database-cbd05.firebaseapp.com',
    storageBucket: 'payroll-database-cbd05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFJ0q2RdvJRgiTkCp-oQM0XMU1nrmdWjY',
    appId: '1:373805444677:android:99b326e279691d1c77fd2c',
    messagingSenderId: '373805444677',
    projectId: 'payroll-database-cbd05',
    storageBucket: 'payroll-database-cbd05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7T4t-VjSM-3Vr7921zw0lsSh1uB_Zrh0',
    appId: '1:373805444677:ios:9c8e76f8eb90468177fd2c',
    messagingSenderId: '373805444677',
    projectId: 'payroll-database-cbd05',
    storageBucket: 'payroll-database-cbd05.appspot.com',
    iosClientId: '373805444677-1a6lddq7sdqf5nslta79bu9d8ic7pa93.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7T4t-VjSM-3Vr7921zw0lsSh1uB_Zrh0',
    appId: '1:373805444677:ios:9c8e76f8eb90468177fd2c',
    messagingSenderId: '373805444677',
    projectId: 'payroll-database-cbd05',
    storageBucket: 'payroll-database-cbd05.appspot.com',
    iosClientId: '373805444677-1a6lddq7sdqf5nslta79bu9d8ic7pa93.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukom',
  );
}
